config/routes.rb
Rails.application.routes.draw do

  resources :customers, only: [:index]
  devise_for :users
  root "dashboard#index"
  get "angular_test", to: "angular_test#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  scope :search, ->(where_clause, args, order_clause){where(where_clause, args).order order_clause}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  PAGE_SIZE = 10

  def index
    @page = params[:page].to_i || 0
    @customers = if params[:keywords].present?
      customer_search_term = CustomerSearchTerm.new params[:keywords]
      Customer.search(customer_search_term.where_clause,
        customer_search_term.where_args, customer_search_term.order)
        .offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      []
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @customers}
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
  <header>
    <h1 ng-if="name">Hello, {{name}}</h1>
  </header>
  <section>
    <form class="form-inline">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" name="name" type="text" placeholder="Enter your name" autofocus ng-model="name">
      </div>
    </form>
  </section>
</article>

app/views/customers/_pager.html.erb
<nav>
  <ul class="pager">
    <li class="previous<%= " disabled" if page == 0 %>"><%= link_to '<span aria-hidden="true">&larr;</span> Previous'.html_safe, customers_path(page: page - 1, keywords: keywords) %></li>
    <li class="next"><%= link_to 'Next <span aria-hidden="true">&rarr;</span>'.html_safe, customers_path(page: page + 1, keywords: keywords) %></li>
  </ul>
</nav>

app/views/customers/index.html.erb
<article ng-app="customers" ng-controller="CustomerSearchController">
  <header>
    <h1 class="h2">Customer Search</h1>
  </header>
  <section class="search-form">
    <form>
      <div class="input-group input-group-lg">
        <label for="keywords" class="sr-only">Keywords</label>
        <input type="text" name="keywords" class="form-control input-lg" placeholder="First Name, Last Name, or Email Address" ng-model="keywords">
        <span class="input-group-btn">
          <button class="btn btn-primary btn-lg" ng-click="search(keywords)">Find Customers</button>
        </span>
      </div>
    </form>
    <h1 class="searchedFor" ng-if="searchedFor"><small>Searched For: </small>{{searchedFor}}</h1>
  </section>
  <section class="search-results">
    <%= render partial: "pager", locals: {page: @page, keywords: params[:keywords]} %>
    <ol class="list-group">
      <li class="list-group-item" ng-repeat="customer in customers">
        <h3 class="pull-right">
          <small class="text-uppercase">Joined</small>
          {{customer.created_at | date}}
        </h3>
        <h2 class="h3">
          {{customer.first_name}} {{customer.last_name}}
          <small>{{customer.username}}</small>
        </h2>
        <h4>{{customer.email}}</h4>
      </li>
    </ol>
    <%= render partial: "pager", locals: {page: @page, keywords: params[:keywords]} %>
  </section>
</article>

app/views/dashboard/index.html.erb
<header>
  <h1>Welcome to Shine!, <%= current_user.email %></h1>
  <h2>We're using Rails <%= Rails.version %></h2>
</header>
<section>
  <p>Future home of Shine's Doshboard</p>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shine</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<% if notice.present? %>
  <aside class="alert alert-info"><%= notice %></aside>
<% end %>
<% if alert.present? %>
  <aside class="alert alert-danger"><%= alert %></aside>
<% end %>
<%= yield %>

</body>
</html>